DROP TABLE objectives IF EXISTS;
DROP TABLE stakeholders IF EXISTS;
DROP TABLE specifications IF EXISTS;



CREATE TABLE types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE specifications (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80),
  description    VARCHAR(80),
  notes       VARCHAR(255)
);
CREATE INDEX specifications_name ON specifications (name);

CREATE TABLE stakeholders (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(80),
  specification_id    INTEGER NOT NULL,
  description VARCHAR(80),
  notes varchar(255)
);
ALTER TABLE stakeholders ADD CONSTRAINT fk_stake_spec FOREIGN KEY (specification_id) REFERENCES specifications (id);
CREATE INDEX stakeholders_name ON stakeholders (name);

CREATE TABLE objectives (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stakeholder_id      INTEGER,
  name varchar(80),
  create_date  DATE,
  description VARCHAR(80),
  notes VARCHAR(255),
  high_priority boolean
);
ALTER TABLE objectives ADD CONSTRAINT fk_objective_stake FOREIGN KEY (stakeholder_id) REFERENCES stakeholders (id);
CREATE INDEX objective_stake_id ON objectives (stakeholder_id);
