DROP TABLE priority_types IF EXISTS;
DROP TABLE objectives IF EXISTS;
DROP TABLE stakeholders IF EXISTS;
DROP TABLE specifications IF EXISTS;


CREATE TABLE priority_types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20),
  sequence INTEGER
);
CREATE INDEX priorityTypes_name ON priority_types (name);

CREATE TABLE specifications (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(40),
  description    VARCHAR(80),
  notes       VARCHAR(255),
  priority_id  INTEGER
);
CREATE INDEX specifications_name ON specifications (name);

CREATE TABLE specification_templates (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(40),
  description    VARCHAR(80),
  notes       VARCHAR(255),
  priority_id  INTEGER
);
CREATE INDEX specification_templates_name ON specification_templates (name);
ALTER TABLE specification_templates ADD CONSTRAINT spec_template_unique unique (name);

CREATE TABLE stakeholders (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  specification_id    INTEGER NOT NULL,
  name       VARCHAR(40),
  description VARCHAR(80),
  notes varchar(255),
  priority_id  INTEGER
);
ALTER TABLE stakeholders ADD CONSTRAINT fk_stake_spec FOREIGN KEY (specification_id) REFERENCES specifications (id);
CREATE INDEX stakeholders_name ON stakeholders (specification_id, name);

CREATE TABLE stakeholder_templates (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(40),
    description    VARCHAR(80),
    notes       VARCHAR(255),
    priority_id  INTEGER
);
CREATE INDEX stakeholder_templates_name ON stakeholder_templates (name);
ALTER TABLE stakeholder_templates ADD CONSTRAINT stake_template_unique unique (name);


CREATE TABLE objectives (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stakeholder_id      INTEGER,
  name varchar(40),
  description VARCHAR(80),
  notes VARCHAR(255),
  priority_id  INTEGER
);
ALTER TABLE objectives ADD CONSTRAINT fk_objective_stake FOREIGN KEY (stakeholder_id) REFERENCES stakeholders (id);
CREATE INDEX objective_stake_id ON objectives (stakeholder_id);
